app:
    resource: "@AppBundle/Controller/"
    type:     annotation
hello: # The route name
    path:     /hello/{name}
    defaults: { _controller: AppBundle:Hello:index }

login:
    path: /login
    defaults: { _controller: AppBundle:Atm:home}
logout:
    path: /logout

authentication-failure:
    path: /authentication-failure
    methods: GET
    defaults: {__controller: AuthenticationFailureHandler:onAuthenticationFailure}